; bed.g
; called to perform automatic bed compensation via G32
;
; generated by MacNite

;M561
G30 P0 X12.5 Y40  Z-99999 		; probe near 1st leadscrew
G30 P1 X125 Y225 Z-99999 		; probe near 2nd leadscrew
G30 P2 X230 Y40 Z-99999 S3 	    ; probe near 3rd leadscrew

G28 Z0
