; homey.g
; called to home the Y axis
;
; generated by MacNite

G91               ; relative positioning
G1 H2 Z5 F12000   ; lift Z relative to current position
G1 H1 Y-265 F6000; move quickly to Y axis endstop and stop there (first pass)
G90
G1 Y5 F6000   ; go back a few mm
G91
G1 H1 Y-265 F360  ; move slowly to Y axis endstop once more (second pass)
G1 H2 Z-5 F12000  ; lower Z again
G90               ; absolute positioning

;G1 Y120

