; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v2.1.3 on Tue Nov 26 2019 11:04:32 GMT+0100 (Mitteleuropäische Normalzeit)
G28 X0
G28 Y0
G28 Z0

G1 X120 Y120 F12000

; Uncomment the following lines to lift Z after probing
;G91                    ; relative positioning
;G1 S2 Z5 F200          ; lift Z relative to current position
;G90                    ; absolute positioning


