; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.3 on Tue Nov 26 2019 11:04:32 GMT+0100 (Mitteleuropäische Normalzeit)

