; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sat Mar 13 2021 18:31:16 GMT+0800 (中国标准时间)
; Wait for set temperatures to be reached
M116 P1

