; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Tue Aug 18 2020 15:25:40 GMT+0200 (Mitteleuropäische Sommerzeit)

G28
M401 ; deploy Z probe (omit if using bltouch)
G30 P0 X20 Y30 Z-99999 ; probe near a leadscrew
G30 P1 X150 Y270 Z-99999 ; probe near a leadscrew
G30 P2 X270 Y30 Z-99999 S3 ; probe near a leadscrew and calibrate 3 motors
M402 ; retract probe (omit if using bltouch)
