; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Tue Aug 18 2020 15:25:40 GMT+0200 (Mitteleuropäische Sommerzeit)
G1 X150 Y150 F18000				 ; go to center of bed
G91               ; relative positioning
G1 H1 Z-355 F1800 ; move Z down until the endstop is triggered
G90
G1 Z5 F1800
G30
G1 Z5 F1800